cleaning repo
WildCodeSchool/2022-09-JS-Lille-project-2-g1-techlegends pull request #1
Opened 2022-10-26 08:48 UTC by hswiergiel

2022-10-26 10:09 UTC, Sax593 requested changes
Passage de CSS a Style component

2022-10-26 13:10 UTC, Sax593 approved these changes

2022-10-27 07:32 UTC, LoicBrassart requested changes
Some Evils to fix, but nothing too bad

2022-10-27 07:32 UTC, LoicBrassart commented on frontend/src/App.jsx
> +import ResetCSS from "./ResetCSS";
Always import the reset **before** your styles, otherwise the reset risks taking the advantage

2022-10-27 07:32 UTC, LoicBrassart commented on frontend/src/ResetCSS.jsx
> +import styled from "styled-components";
That's an unusual approach to a reset-css
Look how it's usually done [here](https://www.npmjs.com/package/reset-css#usage)

2022-10-27 07:32 UTC, LoicBrassart commented on package.json
> +    "styled-components": "^5.3.6"
Nope, that shouldn't be here: this is the package.json file for the wholerepo, not the frontend part
Please remove these changes

2022-10-27 07:32 UTC, LoicBrassart commented on frontend/src/style.jsx
> +  background-color: red;
If that's not the real color of your website (Note: I hope it's not !), remove this test code

2022-10-27 12:48 UTC, hswiergiel commented on frontend/src/App.jsx
> +import ResetCSS from "./ResetCSS";
done!

2022-10-27 12:48 UTC, hswiergiel commented on frontend/src/ResetCSS.jsx
> +import styled from "styled-components";
done, thanks!

2022-10-27 12:51 UTC, hswiergiel commented on package.json
> +    "styled-components": "^5.3.6"
done!

2022-10-27 12:51 UTC, hswiergiel commented on frontend/src/style.jsx
> +  background-color: red;
yes it was not, :) removed!

2022-10-27 13:10 UTC, Sax593 approved these changes

2022-10-27 13:17 UTC, Sax593 approved these changes

2022-10-27 13:31 UTC, LoicBrassart commented
Missing the SM's validation

2022-10-27 14:20 UTC, LoicBrassart approved these changes
Saw no Evil

2022-10-28 06:54 UTC, merged