Integration v02
WildCodeSchool/2022-09-JS-Lille-project-2-g1-techlegends pull request #11
Opened 2022-11-10 11:13 UTC by Atouzani7

Adding 
- autoplay video 
- random 
- count 
- timer

2022-11-10 11:17 UTC, guenk approved these changes
NO evil

2022-11-10 17:24 UTC, LoicBrassart requested changes
Please remove useless React imports

2022-11-10 17:24 UTC, LoicBrassart commented on frontend/src/components/Timer/Timer.jsx
> +import React, { useState, useEffect } from "react";
Stop important React

2022-11-10 17:24 UTC, LoicBrassart commented on frontend/src/components/Toastify/Toast.jsx
> +import React from "react";
Stop important React

2022-11-14 15:38 UTC, guenk approved these changes
well done

2022-11-15 12:55 UTC, LoicBrassart approved these changes
Saw no Evil

2022-11-15 15:52 UTC, merged