Backend
WildCodeSchool/2022-09-JS-Lille-project-2-g1-techlegends pull request #15
Opened 2022-11-17 14:02 UTC by Sax593

2022-11-17 15:02 UTC, guenk approved these changes
evil dead III

2022-11-17 15:24 UTC, LoicBrassart requested changes
One line of dead code... Too bad :p

2022-11-17 15:24 UTC, LoicBrassart commented on backend/src/controllers/usersHandlers.js
> +  // const id = parseInt("req.params.id");
Dead code

2022-11-18 10:44 UTC, guenk approved these changes
10/10

2022-11-18 16:05 UTC, LoicBrassart approved these changes
No more Evils !

2022-11-20 09:02 UTC, merged