Integration
WildCodeSchool/2022-09-JS-Lille-project-2-g1-techlegends pull request #6
Opened 2022-11-04 10:32 UTC by Sax593

2022-11-04 10:39 UTC, guenk approved these changes
perfect 10/10

2022-11-08 19:33 UTC, LoicBrassart requested changes
Saw almost no Evil
... Haven't I reviewed a **very** similar code in your other PR this morning ? Please don't duplicate your components on several branches, it makes my job harder -_-

2022-11-08 19:33 UTC, LoicBrassart commented on package.json
> +    "prop-types": "^15.8.1"
Should be in the frontend :(

2022-11-09 09:56 UTC, LoicBrassart approved these changes
No more Evil!

2022-11-09 10:15 UTC, merged